<a href="https://colab.research.google.com/github/ChnssA/deep-learning-subject/blob/main/deep_learning_labsheet_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1:

```
# Exercise 1: Refresh NumPy
▪ Shape and type of the array
▪ Access specific elements of a 2D NumPy array
▪ Show how to slice a NumPy array to get all rows, but only the first two columns.
▪ Reshape a 1D array of size 12 into a 2D array with 3 rows and 4 columns?
▪ Perform matrix multiplication between two 2D arrays using NumPy.
▪ Compute the mean, median, and standard deviation of a NumPy array
▪ Perform vertical and horizontal stacking in NumPy
▪ Flatten a 3 x 4 NumPy array into a 1D array.
▪ Generate a random array of size n with values drawn from a normal distribution
▪ Perform element-wise addition, subtraction, multiplication, and division
```






In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)
print(arr.dtype)  # Output: int64 (or int32 depending on system)

(2, 3)
int64


In [ ]:
# Accessing the element in the 2nd row, 3rd column
element = arr[1, 2] # Returns 6

In [ ]:
import numpy as np

# Set print options for better readability
np.set_printoptions(precision=2, suppress=True)

print("--- 1. Shape and Type ---")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array:\n{arr}")
print(f"Shape: {arr.shape}")
print(f"Data Type: {arr.dtype}\n")

print("--- 2. Access Specific Elements ---")
# Accessing row 1, column 2 (element '6')
val = arr[1, 2]
print(f"Element at [1, 2]: {val}\n")

print("--- 3. Slicing (All rows, first two columns) ---")
slice_arr = arr[:, :2]
print(f"Sliced Array:\n{slice_arr}\n")

print("--- 4. Reshape 1D (size 12) to 2D (3x4) ---")
arr_1d = np.arange(12)
arr_reshaped = arr_1d.reshape(3, 4)
print(f"Original 1D: {arr_1d}")
print(f"Reshaped 2D (3x4):\n{arr_reshaped}\n")

print("--- 5. Matrix Multiplication ---")
mat_a = np.array([[1, 2], [3, 4]])
mat_b = np.array([[5, 6], [7, 8]])
product = mat_a @ mat_b
print(f"Matrix A:\n{mat_a}")
print(f"Matrix B:\n{mat_b}")
print(f"Result (A @ B):\n{product}\n")

print("--- 6. Mean, Median, and Std Dev ---")
stats_arr = np.array([10, 2, 38, 24, 5, 12])
print(f"Data: {stats_arr}")
print(f"Mean: {np.mean(stats_arr):.2f}")
print(f"Median: {np.median(stats_arr)}")
print(f"Std Dev: {np.std(stats_arr):.2f}\n")

print("--- 7. Vertical and Horizontal Stacking ---")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(f"Vertical Stack:\n{np.vstack((v1, v2))}")
print(f"Horizontal Stack: {np.hstack((v1, v2))}\n")

print("--- 8. Flatten a 3x4 Array ---")
# Using the reshaped array from step 4
flattened = arr_reshaped.flatten()
print(f"Flattened Array: {flattened}\n")

print("--- 9. Random Normal Distribution (size n=5) ---")
n = 5
random_data = np.random.randn(n)
print(f"Random Normal Array:\n{random_data}\n")

print("--- 10. Element-wise Operations ---")
x = np.array([10, 20, 30])
y = np.array([2, 4, 6])
print(f"x: {x}, y: {y}")
print(f"Add:      {x + y}")
print(f"Subtract: {x - y}")
print(f"Multiply: {x * y}")
print(f"Divide:   {x / y}")

--- 1. Shape and Type ---
Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64

--- 2. Access Specific Elements ---
Element at [1, 2]: 6

--- 3. Slicing (All rows, first two columns) ---
Sliced Array:
[[1 2]
 [4 5]]

--- 4. Reshape 1D (size 12) to 2D (3x4) ---
Original 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 2D (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

--- 5. Matrix Multiplication ---
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Result (A @ B):
[[19 22]
 [43 50]]

--- 6. Mean, Median, and Std Dev ---
Data: [10  2 38 24  5 12]
Mean: 15.17
Median: 11.0
Std Dev: 12.33

--- 7. Vertical and Horizontal Stacking ---
Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]

--- 8. Flatten a 3x4 Array ---
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

--- 9. Random Normal Distribution (size n=5) ---
Random Normal Array:
[-0.22  0.83 -0.44 -0.1  -0.64]

--- 10. Element-wise Operations ---
x: [10 20 30], y: [2 4 6]
Add:      [12 24 36]
Subtract: 